### ISSUE TITLE
`.` could not repeat

### ISSUE THREAD

**Issue by MahbubAlam231** [tpope/vim-repeat#64] opened 2018-06-25 20:03 UTC
I performed the operation-- `ysiw"`
I then went to another word and pressed `.` , it did not repeat, it performed `ysiw` and waited for me to to press `"`
It happened with all other similar operations. What's wrong?

**Comment by ironhouzi** [comment] 2018-06-30 10:02
I've been experiencing similar issues. Can I ask what version of Vim you're using?

**Comment by tpope** [comment] 2018-06-30 17:51
You two have repeat.vim installed, correct?

**Comment by ironhouzi** [comment] 2018-07-01 10:19
Yes, it's an issue of #59 for me.

**Comment by tpope** [comment] 2018-07-01 21:54
That was a dumb question on my part, thought this was the surround repo @MahbubAlam231 does #59 fit for you too?

**Comment by MahbubAlam231** [comment] 2018-07-02 08:28
Yes, #59 fit for me too, though I can't tell if TextChanged event is the only one causing the problem.

**Comment by tpope** [comment] 2018-07-02 19:36
Closing as a dupe of #59 then.

**Closed by tpope** 2018-07-02 19:36 UTC
